FROM centos:7

RUN yum -y update \
     install curl \
     centos-release-scl \
     rh-python36 \


RUN cd /var/tmp && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

RUN pip install musicbrainzngs

COPY ./ /tmp/

# RUN yum -y install curl \
#         systemd \
#         initscripts \
#         firewalld \
#         less \
#         vim
#RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
#systemd-tmpfiles-setup.service ] || rm -f $i; done); \
#rm -f /lib/systemd/system/multi-user.target.wants/*;\
#rm -f /etc/systemd/system/*.wants/*;\
#rm -f /lib/systemd/system/local-fs.target.wants/*; \
#rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
#rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
#rm -f /lib/systemd/system/basic.target.wants/*;\
#rm -f /lib/systemd/system/anaconda.target.wants/*;
#VOLUME [ "/sys/fs/cgroup" ]
# RUN yum install -y ansible sudo cronie openssh openssh-server 

#    curl -o /usr/bin/systemctl "https://raw.githubusercontent.com/gdraheim/docker-systemctl-images/master/files/docker/systemctl.py"
# RUN cd /var/tmp && \
#     curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
#     python get-pip.py && \
#     rm get-pip.py
# RUN pip install boto boto3